CREATE TABLE produtos(
    nome varchar(70) NOT NULL,
    preco FLOAT(5,2) NOT NULL,
    created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modified timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    id integer PRIMARY KEY AUTO_INCREMENT
);